export const add = (a: number, b: number) => a + b;
export const subtract = (a: number, b: number) => a - b;
export const multiply = (a: number, b: number) => a * b;
export const divide = (a: number, b: number) => a / b;
export const modulo = (a: number, b: number) => a % b;
export const power = (a: number, b: number) => a ** b;
export const square = (a: number) => a * a;
export const cube = (a: number) => a * a * a;
export const squareRoot = (a: number) => Math.sqrt(a);
export const cubeRoot = (a: number) => Math.cbrt(a);
export const absolute = (a: number) => Math.abs(a);
